version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
        target-branch: "develop"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps): "
    reviewers:
      - "leonardoalvarez20"