### Create User
POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name": "newuser",
    "last_name": "new",
    "email": "newuser@example.com",
    "phone": "6113228",
    "password": "leo"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "leo"
}